config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources :users, except: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  resources :tags, only: [:index, :show]
  resources :votes, only: [:create]

  resources :questions, except: [:destroy] do
      resources :responses, only: [:new, :create]
      resources :answers, only: [:new, :create, :destroy, :edit, :update] do
        resources :responses, only: [:new, :create]
    end
  end

  resources :answers, only: [:update]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :responses, as: :responsible
  has_many :votes, as: :voteable

  validates :content, :user, :question, presence: true

  def vote_count
    self.votes.where(vote_status:true).length - self.votes.where(vote_status:false).length
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :responses, as: :responsible
  has_many :votes, as: :voteable
  has_many :tag_questions
  has_many :tags, through: :tag_questions

  validates :content, :title, :user, presence: true


  def vote_count
    self.votes.where(vote_status: true).length - self.votes.where(vote_status: false).length
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :responsible, polymorphic: true
  belongs_to :user

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tag_questions
  has_many :questions, through: :tag_questions

  validates :name, uniqueness: true, presence: true
end

app/models/tag_question.rb
class TagQuestion < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag

  # validates :tag, :question, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :questions
  has_many :votes
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    if @answer.save
      flash[:notice] = "Your answer was posted!"
      redirect_to @question
    else
      flash.now[:notice] = "Your answer was not posted correct."
      # @question = Question.new
      render "questions/show"
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
      @answer =  Answer.find(params[:id])
    if params[:question_id]
      @question = Question.find(params[:question_id])

      if @answer.update(answer_params)
        redirect_to question_path(@question)
      else
        flash.now[:notice] = "Your edit did not work."
         redirect_to question_path(@question)
          end
    else
       if  !!Answer.find_by(best:true)
         Answer.find_by(best:true).update(best:false)
       end
         @answer.update(best:true)
       redirect_to question_path(@answer.question)

    end
   end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    flash[:notice] = "You deleted your answer!"
    redirect_to @answer.question
  end

  private
  def answer_params
    params.require(:answer).permit(:content, :question_id).merge(user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :logged_in?, except: [:index, :show]

  helper_method :current_user, :author?, :asker?


  def current_user
  	User.find(session[:user_id]) if session[:user_id]
  end

  def author?(answer)
    current_user && (current_user.id == answer.user_id)
  end

  def asker?(question)
    current_user && (current_user.id == question.user_id)
  end


  private

  def logged_in?
  	unless !!current_user
  		flash.alert = "Please Log In"
  		render '/sessions/new'
  	end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order("created_at DESC")
    @vote = Vote.new
  end

  def show
    find_this_question
    @answers = @question.answers
    @answer = Answer.new
    @vote = Vote.new
    @tags = @question.tags
  end

  def new
    @question = Question.new
    @tags = Tag.all
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "Your question was posted!"
      redirect_to @question
    else
      flash.now[:notice] = "Your question was not posted correct."
      # @question = Question.new
      render "questions/new"
    end
  end

  def edit
    find_this_question
  end

  def update
    find_this_question
    @question.assign_attributes(question_params)
    if @question.save
      flash[:notice] = "Your question was successfully updated."
      redirect_to @question
    else
      flash.now[:notice] = "Your question could not be updated."
      render "questions/edit"
    end
  end

  private

  def find_this_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :content, {tag_ids: []}).merge(user_id: current_user.id)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

def new
  if params[:answer_id]
    @responsible = "Answer"
    @responded_id = params[:answer_id]
    @response = Response.new
    @answer = Answer.find(params[:answer_id])
    @path = [@answer.question, @answer,  @response]
 else
    @responsible = "Question"
    @responded_id = params[:question_id]
    @answer = Answer.find(@responded_id)
    @response = Response.new
    @path = [Question.find(@responded_id), @response]
    end
end

def create
  @response = Response.new(response_params)
  @response.update(responsible_type: params[:responsible_type], responsible_id: params[:responsible_id])
 if @response.save
    flash[:notice] = "Your response was posted!"
    if @response.responsible == Question.find(@response.responsible.id)
    redirect_to @response.responsible
  else
    redirect_to @response.responsible.question
  end
 else
    flash.now[:notice] = "Your response was not posted correct."
    render "responses/new"
 end
end

private
  def response_params
    params.require(:response).permit(:responsible_type, :responsible_id, :content).merge(user_id: current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_action :logged_in?


	def new
		render '/sessions/new'
	end

	def create
		@user = User.find_by(email: params[:email])

		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to '/'
		else
			flash[:notice] = "Please Try Again"
			render '/sessions/new'
		end

	end

	def destroy
		session.clear
		IntercomRails::ShutdownHelper::intercom_shutdown_helper(cookies)
		binding.pry
		redirect_to '/'
	end

	def shutdown_intercom
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find(params[:id])
    @questions = @tag.questions
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_action :logged_in?

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to '/'
		else
			flash[:notice] = "You did something wrong"
			render "/users/new"
		end
	end


	def show
		@user = User.find(params[:id])
		@questions = @user.questions
	end


	private

	def user_params
		params.require(:user).permit(:email, :password)
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create

    my_vote = Vote.find_by(voteable_type: params[:voteable_type], voteable_id: params[:voteable_id], user_id: current_user.id)

     if my_vote == nil
        vote = Vote.create(vote_params)
        redirect_to :back
      else
        my_vote.vote_status = params[:vote_status]
        my_vote.save
        redirect_to :back
      end
end

  private

  def vote_params
    params.permit(:voteable_type, :voteable_id, :vote_status).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%=form_for [@question, @answer] do |f|%>
  <%=f.label :content %>
  <%=f.text_area :content, size: "30"%>
  <%=f.submit "Submit"%>
<%end%>

app/views/answers/edit.html.erb
<%=render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoveStack</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <header>
    <nav>
      <ul>
      	<li> <%= link_to "LoveStack", '/' %> </li>
        <li> <%=link_to "Tags", tags_path %> </li>
         <% if current_user %>
          <li> <%= link_to "#{current_user.email}", "/users/#{current_user.id}" %></li>
          <li> <%= link_to "Log Out", "/sessions/#{current_user.id}", method: :delete %> </li>
          <% else %>
          <li><%= link_to "Log In", "/sessions/new" %></li>

          <li><%= link_to "Join LoveStack", "/users/new" %></li>
          <% end %>
      </ul>
    </nav>
  </header>
  <% if flash[:notice] %>
    <div>
      <%= flash[:notice] %>
    </div>
  <%end%>

  <main>
    <%= yield %>
  </main>

</body>
</html>

app/views/questions/_form.html.erb
<div class = question-form><%=form_for(@question) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title%>

  <p><%=f.label :tags %><br>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) %><br></p>


  <%= f.label :content %>
  <%=f.text_area :content, size: "30" %>
  <%=f.submit%>
<% end %>
</div>

app/views/questions/_recent.html.erb
<h1> Recent Questions </h1>

app/views/questions/edit.html.erb
<h1>Edit Your Post</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1> Questions </h1>

<%= link_to "Submit a Question", new_question_path %>

<% @questions.each do |question| %>
<section>
  <h4><%=link_to question.title, question_path(question.id) %></h4>
  <p class = "light small"><%=question.user.email%>, Vote Count:<%=question.vote_count%></p>
  <div class = "vote-up"><%= form_for @vote, url: {action:"create", controller: "votes"} do |f| %>
    <%= hidden_field_tag :voteable_type, "Question" %>
    <%= hidden_field_tag :voteable_id, question.id %>
    <%= hidden_field_tag :vote_status, true %>

    <%= f.submit "UpVote"%>
  <%end%>
</div>

<div class = "vote-down"><%= form_for @vote, url: {action:"create", controller: "votes"} do |f| %>
    <%= hidden_field_tag :voteable_type, "Question" %>
    <%= hidden_field_tag :voteable_id, question.id %>
    <%= hidden_field_tag :vote_status, false %>

    <%= f.submit "DownVote"%>
  <%end%>
</div>
</section>
<% end %>

app/views/questions/new.html.erb
<h1>Post Your Question</h1>

  <%=render "form"%>

app/views/questions/show.html.erb
<section>
  <h2><%=@question.title%></h2>
  <p><%=@question.content%></p>
  <p>Tags:</p>
  <%@tags.each do |tag|%>
  <%=link_to tag.name, tag%>
  <%end%>
  <p> <%=@question.vote_count%></p>
  <div class = "vote-up">
<%= form_for @vote, url: {action:"create", controller: "votes"} do |f| %>
    <%= hidden_field_tag :voteable_type, "Question" %>
    <%= hidden_field_tag :voteable_id, @question.id %>
    <%= hidden_field_tag :vote_status, true %>

    <%= f.submit "UpVote"%>
  <%end%>
</div>

  <div class = "vote-down">
<%= form_for @vote, url: {action:"create", controller: "votes"} do |f| %>
    <%= hidden_field_tag :voteable_type, "Question" %>
    <%= hidden_field_tag :voteable_id, @question.id %>
    <%= hidden_field_tag :vote_status, false %>

    <%= f.submit "DownVote"%>
  <%end%>
  </div>
</section>

<section>
  <h5>Responses</h5>
  <%@question.responses.each do |response| %>
  <section>
    <p>Response by: <%=response.user.email %>: <%=response.content %></p>
    </section>
  <% end %>
  </section>

<section>
    <%= link_to "Submit a response!", new_question_response_path(@question)%>
</section>

<p>-----------------------</p>

<h3> Answers For This Question</h3>

<section class = "answer-form">
  <%if current_user %>
    <%=render 'answers/form' %>
  <%end%>
</section>

<% @answers.each do |answer| %>
 <section>

  <%if asker?(@question) && !answer.best%>
    <%=link_to "Choose as most helpful", answer_path(answer), :method=> :put %>
  <%elsif answer.best%>
<img src="http://findicons.com/files/icons/2166/oxygen/48/checkmark_korganizer.png" alt="Best answer">
  <%end%><br><br>
  By: <%=link_to answer.user.email, answer.user %> at: <%=answer.created_at%><br>
   <%=answer.content %><br><br>
   Vote Count: <%=answer.vote_count%>
     <div class = "vote-up">
  <%= form_for @vote, url: {action:"create", controller: "votes"} do |f| %>
    <%= hidden_field_tag :voteable_type, "Answer" %>
    <%= hidden_field_tag :voteable_id, answer.id %>
    <%= hidden_field_tag :vote_status, true %>

    <%= f.submit "UpVote"%>
  <%end%>
</div>

<div class = "vote-down"><%= form_for @vote, url: {action:"create", controller: "votes"} do |f| %>
    <%= hidden_field_tag :voteable_type, "Answer" %>
    <%= hidden_field_tag :voteable_id, answer.id %>
    <%= hidden_field_tag :vote_status, false %>

    <%= f.submit "DownVote"%>
  <%end%>
  </div><br>
    <%= link_to "Respond to this answer!", new_question_answer_response_path(@question, answer)%>
    <% if author?(answer)%>
    <%=link_to "Edit Answer", edit_question_answer_path(@question, answer) %>
    <%=link_to 'delete answer', [@question, answer], method: :delete, data: {confirm: 'Sure about that?'}%>
  <%end%>

   </section>

  <section>
  <h4>Response to <%=answer.user.email%></h4>
  <%answer.responses.each do |response| %>
  <section>
    <h5>Response by: <%=response.user.email %></h5> <p><%=response.content %></p>
    </section>
  <% end %>
  </section>

<%end%>

app/views/responses/new.html.erb
"Make a quick response"


<div class = question-form><%=form_for @path do |f| %>
  <%= f.label :content %>
  <%=f.text_area :content, size: "30" %>
   <%= hidden_field_tag :responsible_type, @responsible %>
   <%= hidden_field_tag :responsible_id, @responded_id %>
  <%=f.submit%>
<% end %>
</div>

app/views/tags/index.html.erb
<h1> Tags Page</h1>
<br>

 <% @tags.each do |tag| %>
 	<div>
		<%= link_to(tag.name, tag)%>
 	</div>
 <% end %>

app/views/tags/show.html.erb
<h1> <%= @tag.name %> Tag Page</h1>

<section>
<% @questions.each do |question| %>
  <%=link_to question.title, question_path(question)%>
<% end %>
</section>

app/views/users/new.html.erb
<h1> Sign Up Here</h1>

<%= form_for @user, url: {action: 'create', controller: "users"} do |f| %>
<%= f.label :email %>
<%= f.text_field :email%>

<%= f.label :password %>
<%= f.password_field :password%>

<%= f.submit "Join The Love!" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email%>'s Profile Page</h1><br>
<h2><%= @user.email%>'s Questions</h2><br>

<%@questions.each do |question| %>
  <p>
    <%=link_to question.title, question%>
  </p>
<%end%>